# This workflow will upload a Python Package using Twine when a release is created
# It builds and uploads documentation automatically afterwards using pdoc
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install pdoc
    - name: Build package
      run: python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
    - name: Build documentation using pdoc
      run: |
        pdoc -d google -o ./build ./nn_tuning
    - name: Deploy documentation to GitHub Pages 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: github_pages # The branch the action should deploy to.
        folder: build # The folder the action should deploy.
